---
name: CI PR Builds
'on':
  push:
    branches:
    - master
  pull_request:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '2.4'
        - '2.5'
        - '2.7'
        - '3.0'
        activerecord:
        - '5.1'
        - '5.2'
        - '6.0'
        exclude:
        - ruby: '2.4'
          activerecord: '6.0'
        - ruby: '3.0'
          activerecord: '5.1'
        - ruby: '3.0'
          activerecord: '5.2'
    env:
      BUNDLE_GEMFILE: "${{ github.workspace }}/gemfiles/activerecord-${{ matrix.activerecord }}.gemfile"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - name: Run bundle update
      run: bundle update
    - name: Run tests
      run: bundle exec rspec
    - name: Run rubocop
      run: bundle exec rubocop
